import { Link } from "react-router-dom";
import { Play } from "lucide-react";

const HeroSection = () => {
  return (
    <section id="home" className="pt-20 sm:pt-32 pb-20 px-4 md:pb-32 hero-gradient relative overflow-hidden">
      <div className="container mx-auto max-w-6xl relative z-10">
        <div className="flex flex-col lg:flex-row items-center gap-10">
          <div className="flex-1 text-center lg:text-left max-w-2xl mx-auto lg:mx-0">
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold mb-6 leading-tight tracking-tight">
              Personalized AI Meditations for Your <span className="text-gradient">Wellbeing</span> Journey
            </h1>
            <p className="text-xl text-foreground/80 mb-10">
              Experience custom-crafted meditations generated by AI to match your unique needs, style preferences, and goals.
            </p>
            <div className="flex flex-col sm:flex-row justify-center lg:justify-start gap-4 sm:gap-6">
              <Link 
                to="/auth"
                className="btn-primary-gradient text-base px-8 py-3 h-auto"
              >
                Start for Free
              </Link>
              <a 
                href="https://www.loom.com/share/7c72ce5c236149beb893f7d57b23af34?sid=fd55d113-5e4d-400b-8b7b-f042fbada946"
                target="_blank"
                rel="noopener noreferrer"
                className="btn-secondary flex items-center justify-center text-base px-8 py-3 h-auto gap-2"
              >
                <Play size={18} /> Watch Video
              </a>
            </div>
          </div>

          <div className="flex-1 relative mt-8 lg:mt-0">
            <div className="relative flex items-center justify-center lg:justify-start">
              <div className="absolute w-[280px] h-[560px] lg:w-[320px] lg:h-[640px] lg:ml-40 rounded-[3rem] bg-blue-500/20 blur-[60px] -z-10"></div>
              
              <div className="relative w-[280px] h-[560px] lg:w-[320px] lg:h-[640px] lg:ml-40 animate-float">
                <img 
                  src="/Mockup.png"
                  alt="Serene Symphony App Interface"
                  className="w-full h-full object-contain drop-shadow-2xl"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-1/4 left-1/4 w-[500px] h-[500px] rounded-full bg-blue-400/20 blur-[100px]"></div>
        <div className="absolute bottom-1/4 right-1/4 w-[600px] h-[600px] rounded-full bg-blue-500/20 blur-[120px]"></div>
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] rounded-full bg-cyan-400/20 blur-[150px]"></div>
      </div>
      
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-1/4 left-1/3 h-32 w-32 rounded-full bg-blue-300/30"></div>
        <div className="absolute bottom-1/4 right-1/3 h-48 w-48 rounded-full bg-purple-200/30"></div>
        <div className="absolute top-2/3 left-1/2 h-24 w-24 rounded-full bg-green-200/30"></div>
      </div>
    </section>
  );
};

export default HeroSection;
