
import { Link } from "react-router-dom";
import { Play } from "lucide-react";

const HeroSection = () => {
  return (
    <section id="home" className="pt-20 sm:pt-32 pb-20 px-4 md:pb-32 hero-gradient relative overflow-hidden">
      <div className="container mx-auto max-w-6xl relative z-10">
        <div className="flex flex-col lg:flex-row items-center gap-12">
          <div className="flex-1 text-center lg:text-left max-w-2xl mx-auto lg:mx-0">
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold mb-6 leading-tight tracking-tight">
              Personalized AI Meditations for Your <span className="text-gradient animate-pulse-soft">Wellbeing</span> Journey
            </h1>
            <p className="text-xl text-foreground/80 mb-10">
              Experience custom-crafted meditations generated by AI to match your unique needs, style preferences, and goals.
            </p>
            <div className="flex flex-col sm:flex-row justify-center lg:justify-start gap-4 sm:gap-6">
              <Link 
                to="/auth"
                className="btn-primary-gradient text-base px-8 py-3 h-auto"
              >
                Start for Free
              </Link>
              <button 
                className="btn-secondary flex items-center justify-center text-base px-8 py-3 h-auto gap-2"
              >
                <Play size={18} /> Watch Video
              </button>
            </div>
          </div>
          
          <div className="flex-1 relative">
            <div className="relative flex items-center justify-center">
              <div className="relative w-[320px] h-[640px] lg:w-[360px] lg:h-[720px] animate-float" style={{ animationDelay: "0.5s" }}>
                <img 
                  src="/lovable-uploads/5afb2b1f-aa2a-42a3-bb63-955ccda6c753.png"
                  alt="Meditation App Interface"
                  className="w-full h-full object-contain rounded-[3rem] shadow-2xl transform hover:scale-105 transition-all duration-700"
                />
              </div>
              <div className="absolute -right-8 sm:-right-16 top-[10%] w-[280px] h-[560px] lg:w-[320px] lg:h-[640px] animate-float opacity-75" style={{ animationDelay: "1s" }}>
                <img 
                  src="/lovable-uploads/5afb2b1f-aa2a-42a3-bb63-955ccda6c753.png"
                  alt="Meditation App Secondary View"
                  className="w-full h-full object-contain rounded-[3rem] transform hover:scale-105 transition-all duration-700"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-1/4 left-1/4 w-[500px] h-[500px] rounded-full bg-blue-400/20 blur-[100px] animate-pulse-soft"></div>
        <div className="absolute bottom-1/4 right-1/4 w-[600px] h-[600px] rounded-full bg-blue-500/20 blur-[120px] animate-pulse-soft" style={{ animationDelay: "1s" }}></div>
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] rounded-full bg-cyan-400/20 blur-[150px] animate-pulse-soft" style={{ animationDelay: "2s" }}></div>
      </div>
      
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-1/4 left-1/3 h-32 w-32 rounded-full bg-blue-300/30 animate-float" style={{ animationDelay: "0.5s" }}></div>
        <div className="absolute bottom-1/4 right-1/3 h-48 w-48 rounded-full bg-purple-200/30 animate-float" style={{ animationDelay: "1.2s" }}></div>
        <div className="absolute top-2/3 left-1/2 h-24 w-24 rounded-full bg-green-200/30 animate-breathe" style={{ animationDelay: "0.8s" }}></div>
      </div>
    </section>
  );
};

export default HeroSection;
