// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmycclummbknlsxejjlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndteWNjbHVtbWJrbmxzeGVqamxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0ODM2ODEsImV4cCI6MjA1NTA1OTY4MX0.w7pRL78DVVNcw9dtFmyySkV-ctvrvVMfEoP0ud--0Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);